local Automation = {}
local ModuleLoader = _G.GardenHub and _G.GardenHub.ModuleLoader or error("GardenHub ModuleLoader not initialized")
local Theme = ModuleLoader:Require("ui.Theme")
local State = ModuleLoader:Require("core.State")
local Logger = ModuleLoader:Require("core.Logger")
local AutomationController = ModuleLoader:Require("controllers.AutomationController")
local Dropdown = ModuleLoader:Require("ui.components.Dropdown")
local function panel(parent,title,height)
 local t=Instance.new("TextLabel");t.Size=UDim2.new(1,0,0,20);t.BackgroundTransparency=1;t.Text=title;t.TextColor3=Theme.Text;t.Font=Enum.Font.GothamBold;t.TextSize=12;t.TextXAlignment=Enum.TextXAlignment.Left;t.Parent=parent
 local f=Instance.new("Frame");f.BackgroundColor3=Theme.PanelSecondary;f.BorderSizePixel=1;f.BorderColor3=Theme.Border;f.Size=UDim2.new(1,0,0,height);f.Parent=parent;local c=Instance.new("UICorner");c.CornerRadius=UDim.new(0,10);c.Parent=f;local p=Instance.new("UIPadding");p.PaddingLeft=UDim.new(0,8);p.PaddingRight=UDim.new(0,8);p.Parent=f;local l=Instance.new("UIListLayout");l.Padding=UDim.new(0,4);l.Parent=f;return f
end
local function toggle(parent,text,initial,changed)
 local row=Instance.new("Frame");row.Size=UDim2.new(1,0,0,24);row.BackgroundTransparency=1;row.Parent=parent;local b=Instance.new("TextButton");b.Size=UDim2.new(0,16,0,16);b.Position=UDim2.new(0,0,.5,-8);b.BorderSizePixel=1;b.BorderColor3=Theme.Border;b.Text="";b.Parent=row;local l=Instance.new("TextLabel");l.Position=UDim2.new(0,24,0,0);l.Size=UDim2.new(1,-24,1,0);l.BackgroundTransparency=1;l.Text=text;l.TextColor3=Theme.TextSecondary;l.Font=Enum.Font.Gotham;l.TextSize=12;l.TextXAlignment=Enum.TextXAlignment.Left;l.Parent=row
 local on=initial==true;local connection;local o={};function o:SetState(v)on=v==true;b.BackgroundColor3=on and Theme.Blue or Theme.Disabled end;function o:GetState()return on end;function o:Destroy()if connection and connection.Connected then connection:Disconnect()end;connection=nil;if row then row:Destroy();row=nil end end;o:SetState(on);connection=b.MouseButton1Click:Connect(function()o:SetState(not on);if changed then changed(on)end end);local owner=parent.Parent;if owner and owner.Controls then table.insert(owner.Controls,o)end;return o
end
local function info(parent,text) local l=Instance.new("TextLabel");l.Size=UDim2.new(1,0,0,16);l.BackgroundTransparency=1;l.Text=text;l.TextColor3=Theme.TextSecondary;l.Font=Enum.Font.Gotham;l.TextSize=10;l.TextXAlignment=Enum.TextXAlignment.Left;l.Parent=parent;return l end
function Automation:Build(parent)
 local module=Instance.new("ScrollingFrame");module.Name="AutomationTab";module.Size=UDim2.new(1,0,1,0);module.BackgroundTransparency=1;module.BorderSizePixel=0;module.AutomaticCanvasSize=Enum.AutomaticSize.Y;module.CanvasSize=UDim2.new(0,0,0,0);module.ScrollBarThickness=4;module.Parent=parent;module.Subscriptions={};module.Connections={};module.Controls={};module.Dropdowns={};local layout=Instance.new("UIListLayout");layout.Padding=UDim.new(0,8);layout.Parent=module
 local function subscribe(key, callback) local fn=function(v) callback(v) end;State:Subscribe(key,fn);table.insert(module.Subscriptions,{key,fn}) end
 local farm=panel(module,"FARM MODES",190);local controls={};for _,m in ipairs({{"Auto Farm Seeds V5","V5","Tridenthra x3 · Volcaflora x3"},{"Auto Farm Seeds V4","V4","Lawnmower · Rafflesia · Zapseed"},{"Auto Farm Seeds V2","V2","Lawnmower · Rafflesia"},{"Auto Farm Win","Win","Tomato"}}) do controls[m[2]]=toggle(farm,m[1],State:Get("FarmMode")==m[2],function(on)State:Set("FarmMode",on and m[2] or nil)end);info(farm,m[3])end;subscribe("FarmMode",function(v)for k,c in pairs(controls)do c:SetState(k==v)end end)
 local tick=panel(module,"TICK SPEED",92);local auto=toggle(tick,"Auto Tick Speed",State:Get("AutoTickSpeed",false),function(v)State:Set("AutoTickSpeed",v)end);local x2=toggle(tick,"Speed x2",State:Get("TickSpeed")==2,function(v)State:Set("TickSpeed",v and 2 or 1)end);local x3=toggle(tick,"Speed x3",State:Get("TickSpeed")==3,function(v)State:Set("TickSpeed",v and 3 or 1)end);subscribe("AutoTickSpeed",function(v)auto:SetState(v)end);subscribe("TickSpeed",function(v)x2:SetState(v==2);x3:SetState(v==3)end)
 local options=panel(module,"FARM OPTIONS",112);for _,i in ipairs({{"Auto Equip Units","AutoEquipUnits"},{"Auto Skip Wave","AutoSkipWave"},{"Auto Play Again","AutoPlayAgain"},{"Turn Off Global Play","TurnOffGlobalPlay"}})do local c=toggle(options,i[1],State:Get(i[2],false),function(v)State:Set(i[2],v)end);subscribe(i[2],function(v)c:SetState(v)end)end
 local map=panel(module,"MAP & DIFFICULTY",210);local currentMapLabel=info(map,"Current Map: "..tostring(State:Get("CurrentMap","Unknown")));local currentDifficultyLabel=info(map,"Current Difficulty: "..tostring(State:Get("CurrentDifficulty","Unknown")));info(map,"Select Map");local md=Dropdown.new(map,{"Garden","Volcano","Desert"});md:SetSelected(State:Get("SelectedMap"),true);md:OnChanged(function(v)State:Set("SelectedMap",v)end);info(map,"Select Difficulty");local dd=Dropdown.new(map,{"Normal","Hard","Nightmare"});dd:SetSelected(State:Get("SelectedDifficulty"),true);dd:OnChanged(function(v)State:Set("SelectedDifficulty",v)end);local aj=toggle(map,"Auto Join Map",State:Get("AutoJoinMap",false),function(v)State:Set("AutoJoinMap",v)end);local ad=toggle(map,"Auto Select Difficulty",State:Get("AutoSelectDifficulty",false),function(v)State:Set("AutoSelectDifficulty",v)end);local once=Instance.new("TextButton");once.Size=UDim2.new(1,0,0,26);once.BackgroundColor3=Theme.Blue;once.Text="Join Once";once.TextColor3=Theme.Text;once.Font=Enum.Font.GothamBold;once.TextSize=11;once.Parent=map;table.insert(module.Connections,once.MouseButton1Click:Connect(function()local ok,msg=AutomationController:JoinOnce();if not ok then Logger:Warning(msg or "Join Once requires ConcreteBridge")end end));subscribe("CurrentMap",function(v)currentMapLabel.Text="Current Map: "..tostring(v or "Unknown")end);subscribe("CurrentDifficulty",function(v)currentDifficultyLabel.Text="Current Difficulty: "..tostring(v or "Unknown")end);subscribe("SelectedMap",function(v)md:SetSelected(v,true)end);subscribe("SelectedDifficulty",function(v)dd:SetSelected(v,true)end);subscribe("AutoJoinMap",function(v)aj:SetState(v)end);subscribe("AutoSelectDifficulty",function(v)ad:SetState(v)end)
 local head=Instance.new("TextButton");head.Size=UDim2.new(1,0,0,24);head.BackgroundTransparency=1;head.Text="> MORPH MODE";head.TextColor3=Theme.Text;head.Font=Enum.Font.GothamBold;head.TextXAlignment=Enum.TextXAlignment.Left;head.Parent=module;local morph=panel(module,"",58);morph.Visible=false;local morphEnabled=toggle(morph,"Morph mode enabled",State:Get("MorphMode",false),function(v)State:Set("MorphMode",v)end);local keepMorph=toggle(morph,"Keep current morph",State:Get("KeepCurrentMorph",false),function(v)State:Set("KeepCurrentMorph",v)end);subscribe("MorphMode",function(v)morphEnabled:SetState(v)end);subscribe("KeepCurrentMorph",function(v)keepMorph:SetState(v)end);table.insert(module.Connections,head.MouseButton1Click:Connect(function()morph.Visible=not morph.Visible;head.Text=morph.Visible and "v MORPH MODE" or "> MORPH MODE"end))
 table.insert(module.Dropdowns,md);table.insert(module.Dropdowns,dd);module.Cleanup=function()for _,s in ipairs(module.Subscriptions or {})do State:Unsubscribe(s[1],s[2])end;for _,c in ipairs(module.Connections or {})do if c.Connected then c:Disconnect()end end;for _,control in ipairs(module.Controls or {})do control:Destroy()end;for _,dropdown in ipairs(module.Dropdowns or {})do dropdown:Destroy()end;module.Subscriptions={};module.Connections={};module.Controls={};module.Dropdowns={}end
 return module
end
return Automation
